name       : blosc
version    : 1.20.0
release    : 1
source     :
    - https://github.com/Blosc/c-blosc/archive/v1.20.0.tar.gz : 992ab5b475b7ba94f91c5ce58359ff0d6069fc65ba0c5bee373db8daecb17ce0
license    : 
    - BSD-2-CLAUSE
    - BSD-3-CLAUSE
    - MIT
    - Zlib
component  : programming.library
summary    : A blocking, shuffling and loss-less compression library that can be faster than `memcpy()`
description: |
    Blosc is a high performance compressor optimized for binary data. It has been designed to transmit data to the processor cache faster than the traditional, non-compressed, direct memory fetch approach via a memcpy() OS call.
setup      : |
    %cmake_ninja -DBUILD_STATIC=OFF -DBUILD_TESTS=OFF -DBUILD_FUZZERS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
