name       : blosc
version    : 1.21.0
release    : 2
source     :
    - https://github.com/Blosc/c-blosc/archive/v1.21.0.tar.gz : b0ef4fda82a1d9cbd11e0f4b9685abf14372db51703c595ecd4d76001a8b342d
license    :
    - BSD-2-CLAUSE
    - BSD-3-CLAUSE
    - MIT
    - Zlib
component  : programming.library
summary    : A blocking, shuffling and loss-less compression library that can be faster than `memcpy()`
description: |
    Blosc is a high performance compressor optimized for binary data. It has been designed to transmit data to the processor cache faster than the traditional, non-compressed, direct memory fetch approach via a memcpy() OS call.
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libzstd)
    - snappy-devel
setup      : |
    %cmake_ninja -DBUILD_STATIC=OFF -DBUILD_TESTS=OFF -DBUILD_FUZZERS=OFF \
      -DDEACTIVATE_SNAPPY=OFF -DPREFER_EXTERNAL_LZ4=ON \
      -DPREFER_EXTERNAL_ZLIB=ON -DPREFER_EXTERNAL_ZSTD=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
